### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by lococo14** [lococo14/furima-33471#9]
# URL
https://furima-33471.herokuapp.com/

# Basic認証のIDとパスワード
ID: admin
password: 2222

# 出品者用のメールアドレスとパスワード
email: test@kkk.com
password: mmmmmm123

# 購入者用のメールアドレスとパスワード
email: mimi@dot.com
password: mmmmmm123

# 購入用カードの番号・期限・セキュリティコード
card_number: 4242424242424242
expiration: 7/23
cvc: 123

**Comment by snkw-works** [comment]
@lococo14さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/54050089/105327856-c5a4a300-5c12-11eb-82ed-20fcf194071c.png)
